import contentDefaults from '@/public/content-defaults.json';
import {database,config,initialize} from '@/db/raw';
import {isAllowedAdmin} from '@/lib/admin-policy';
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
function validLaunchGoodUrl(value:unknown){if(typeof value!=='string')return false;try{const u=new URL(value);return u.protocol==='https:'&&['launchgood.com','www.launchgood.com'].includes(u.hostname)&&!u.username&&!u.password&&!u.port&&u.pathname!=='/';}catch{return false;}}
async function launchGoodUrl(){const row=await database().prepare("SELECT value FROM site_content WHERE key='launchgood'").first<{value:string}>();const url=row?JSON.parse(row.value).url:'';return validLaunchGoodUrl(url)?url:'';}
const now=()=>new Date().toISOString();
async function rateLimit(req:Request,action:string){const window=Math.floor(Date.now()/60000);const raw=(req.headers.get('cf-connecting-ip')||req.headers.get('oai-authenticated-user-id')||'anonymous')+':'+action+':'+window;const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw)))).map(x=>x.toString(16).padStart(2,'0')).join('');const db=database();const r=await db.prepare('INSERT INTO rate_limits (id,count,expires) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1 RETURNING count').bind(hash,window+2).first<{count:number}>();await db.prepare('DELETE FROM rate_limits WHERE expires<?').bind(window).run();return (r?.count||0)<=10;}

const emailValid=(s:unknown)=>typeof s==='string'&&s.length<=254&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);
function admin(req:Request){return isAllowedAdmin(req.headers.get('oai-authenticated-user-id'),req.headers.get('oai-authenticated-user-email'),config().ADMIN_EMAILS);}
function ready(){return false;}
async function subscribe(email:string,source:string){await database().prepare('INSERT INTO subscribers (email,token,consent,source,active) VALUES (?,?,?,?,1) ON CONFLICT(email) DO UPDATE SET consent=excluded.consent,source=excluded.source,active=1').bind(email,crypto.randomUUID(),now(),source).run();}
async function log(req:Request,action:string){await database().prepare('INSERT INTO audit (id,actor,action,created) VALUES (?,?,?,?)').bind(crypto.randomUUID(),req.headers.get('oai-authenticated-user-email')||'payment-provider',action,now()).run();}
async function deliver(){const c=config();if(!c.RESEND_API_KEY||!c.EMAIL_FROM)return;const rows=await database().prepare("SELECT * FROM outbox WHERE status='queued' LIMIT 30").all<any>();for(const row of rows.results){if(row.body.includes('Unsubscribe from impact updates:')){const sub=await database().prepare('SELECT active FROM subscribers WHERE email=?').bind(row.email).first<any>();if(!sub?.active){await database().prepare("UPDATE outbox SET status='cancelled' WHERE id=?").bind(row.id).run();continue;}}const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+c.RESEND_API_KEY,'Content-Type':'application/json','Idempotency-Key':row.id},body:JSON.stringify({from:c.EMAIL_FROM,to:[row.email],subject:row.subject,text:row.body})});if(r.ok)await database().prepare("UPDATE outbox SET status='sent' WHERE id=?").bind(row.id).run();}}
export async function GET(req:Request,{params}:{params:Promise<{action:string}>}){try{const {action}=await params;
if(action==='admin'&&!admin(req))return json({error:req.headers.get('oai-authenticated-user-id')?'This ChatGPT account does not have administrator access. Sign in with the account assigned by the site owner.':'Sign in with ChatGPT to open the administrator dashboard.'},req.headers.get('oai-authenticated-user-id')?403:401);
const db=database();await initialize();
if(action==='public'){const campaigns=await db.prepare('SELECT * FROM campaigns').all<any>();const campaignTotals=await db.prepare("SELECT campaign,currency,SUM(amount-refunded) AS total FROM donations WHERE status='succeeded' GROUP BY campaign,currency").all<any>();for(const campaign of campaigns.results)campaign.totals=campaignTotals.results.filter(t=>t.campaign===campaign.id);const totals=await db.prepare("SELECT currency,SUM(amount-refunded) AS total,COUNT(*) AS count FROM donations WHERE status='succeeded' GROUP BY currency").all();const reports=await db.prepare('SELECT * FROM reports ORDER BY created DESC').all();const allocations=await db.prepare('SELECT * FROM allocations ORDER BY updated,id').all();const content=await db.prepare('SELECT * FROM site_content').all<any>();return json({content:Object.fromEntries(content.results.map(r=>[r.key,{value:JSON.parse(r.value),revision:r.revision}])),allocations:allocations.results,campaigns:campaigns.results,totals:totals.results,reports:reports.results,launchGoodReady:!!(await launchGoodUrl()),paymentsReady:false,currency:config().DONATION_CURRENCY||null});}
if(action==='admin'){if(!admin(req))return json({error:'Administrator access has not been granted to this account. Ask the site owner to configure the administrator email allowlist.'},403);const donations=await db.prepare('SELECT * FROM donations ORDER BY created DESC LIMIT 1000').all();const subscribers=await db.prepare('SELECT email,consent,source,active FROM subscribers ORDER BY consent DESC').all();const outbox=await db.prepare('SELECT id,email,subject,status,created FROM outbox ORDER BY created DESC LIMIT 100').all();const activity=await db.prepare('SELECT action,actor,created FROM audit ORDER BY created DESC LIMIT 50').all();return json({accountEmail:req.headers.get('oai-authenticated-user-email'),currency:config().DONATION_CURRENCY||'USD',activity:activity.results,donations:donations.results,subscribers:subscribers.results,outbox:outbox.results,launchGoodUrl:await launchGoodUrl(),paymentsReady:false,emailReady:!!(config().RESEND_API_KEY&&config().EMAIL_FROM)});}
if(action==='status'){const id=new URL(req.url).searchParams.get('session');if(!id||!/^cs_[\w]+$/.test(id))return json({error:'Invalid payment reference'},400);const found=await db.prepare('SELECT status FROM donations WHERE id=?').bind(id).first();return json({confirmed:found?.status==='succeeded'});}
return json({error:'Not found'},404);}catch{return json({error:'We could not load this information. Please try again shortly.'},503);}}
export async function POST(req:Request,{params}:{params:Promise<{action:string}>}){try{const {action}=await params;if(['webhook','checkout','reconcile'].includes(action))return json({error:'On-site payments have been retired. Donations are handled on LaunchGood.'},410);if(req.headers.get('origin')!==new URL(req.url).origin)return json({error:'Invalid request origin'},403);if(action==='content'&&!admin(req))return json({error:'Administrator access required'},403);const limit=action==='content'?3000000:20000;if(Number(req.headers.get('content-length')||0)>limit)return json({error:'Request too large'},413);if(!await rateLimit(req,action))return json({error:'Too many requests. Please wait a minute and try again.'},429);const raw=await req.text();if(raw.length>limit)return json({error:'Request too large'},413);const b=JSON.parse(raw) as any;const db=database();await initialize();
if(action==='launchgood'){const url=await launchGoodUrl();if(!url)return json({error:'Our LaunchGood fundraiser is not open yet. Please check back soon.'},409);if(!emailValid(b.email)||b.consent!==true)return json({error:'Enter a valid email address.'},400);await subscribe(b.email.trim().toLowerCase(),'launchgood-impact-naseem-v1');return json({url});}
if(action==='subscribe'){if(!emailValid(b.email)||b.consent!==true||b.website)return json({error:'Enter a valid email and agree to receive launch news.'},400);await subscribe(b.email.trim().toLowerCase(),'launch-form-v1');return json({ok:true});}
if(action==='unsubscribe'){if(typeof b.token!=='string')return json({error:'Invalid link'},400);await db.prepare('UPDATE subscribers SET active=0 WHERE token=?').bind(b.token).run();return json({ok:true});}
if(!admin(req))return json({error:'Administrator access required'},403);
if(action==='launchgood-settings'){if(typeof b.url!=='string'||(b.url!==''&&!validLaunchGoodUrl(b.url)))return json({error:'Enter an HTTPS LaunchGood fundraiser URL, or leave it blank to close donations.'},400);await db.prepare("INSERT INTO site_content (key,value,revision) VALUES ('launchgood',?,1) ON CONFLICT(key) DO UPDATE SET value=excluded.value,revision=site_content.revision+1").bind(JSON.stringify({url:b.url})).run();await log(req,'Updated LaunchGood fundraiser link');return json({ok:true});}
if(action==='content'){
const validText=(v:unknown,max:number)=>typeof v==='string'&&v.length<=max;
if(typeof b.key!=='string'||!Number.isSafeInteger(b.revision)||b.revision<0)return json({error:'Invalid content request'},400);
if(b.key==='team'){
if(!Array.isArray(b.value)||b.value.length>30||b.value.some((m:any)=>!m||!validText(m.name,120)||!m.name.trim()||!validText(m.role,200)||!validText(m.bio,4000)||!validText(m.photo,150000)||!(m.photo===''||/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(m.photo))))return json({error:'Check team details. Photos must be JPG, PNG or WebP under 110 KB after resizing.'},400);
}else{
const fields=(contentDefaults.pages as Record<string,Array<{id:string,kind?:string}>>)[b.key];
if(!fields||!b.value||typeof b.value!=='object'||Array.isArray(b.value)||Object.keys(b.value).some(k=>!fields.some(f=>f.id===k)))return json({error:'Unknown page or content field'},400);
for(const field of fields){const v=b.value[field.id];if(v!==undefined&&(!validText(v,10000)||(field.kind==='url'&&!/^(https:\/\/|mailto:)[^\s<>]+$/.test(v))))return json({error:'Use plain text and valid HTTPS or email links.'},400);}
}
const result=await db.prepare('INSERT INTO site_content (key,value,revision) SELECT ?,?,1 WHERE ?=0 ON CONFLICT(key) DO UPDATE SET value=excluded.value,revision=site_content.revision+1 WHERE site_content.revision=?').bind(b.key,JSON.stringify(b.value),b.revision,b.revision).run();
// Existing revisions use a separate compare-and-swap update because INSERT SELECT skips existing rows.
if(!result.meta.changes&&b.revision>0){const updated=await db.prepare('UPDATE site_content SET value=?,revision=revision+1 WHERE key=? AND revision=?').bind(JSON.stringify(b.value),b.key,b.revision).run();if(!updated.meta.changes)return json({error:'Someone else edited this content. Reload the editor before saving.'},409);}else if(!result.meta.changes)return json({error:'Content changed. Reload the editor before saving.'},409);
await log(req,'Updated site content: '+b.key);return json({ok:true});}
if(action==='campaign'){if(typeof b.name!=='string'||!b.name.trim()||b.name.length>100||typeof b.description!=='string'||b.description.length>3000||!['active','closed'].includes(b.status)||!Number.isSafeInteger(b.sponsored)||b.sponsored<0||b.sponsored>1000000)return json({error:'Check campaign details'},400);const id=b.id||crypto.randomUUID();await db.batch([db.prepare('INSERT INTO campaigns (id,name,description,status,sponsored) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,description=excluded.description,status=excluded.status,sponsored=excluded.sponsored').bind(id,b.name,b.description,b.status,b.sponsored),db.prepare('INSERT INTO audit (id,actor,action,created) VALUES (?,?,?,?)').bind(crypto.randomUUID(),req.headers.get('oai-authenticated-user-email'),'Campaign saved: '+id,now())]);return json({ok:true});}
if(action==='allocation'||action==='allocation-delete'){
if(typeof b.campaign!=='string'||!await db.prepare('SELECT id FROM campaigns WHERE id=?').bind(b.campaign).first())return json({error:'Choose a campaign'},400);
if(b.id!==undefined&&(typeof b.id!=='string'||!await db.prepare('SELECT id FROM allocations WHERE id=? AND campaign=?').bind(b.id,b.campaign).first()))return json({error:'Allocation no longer exists. Refresh and try again.'},404);
if(action==='allocation-delete'&&!b.id)return json({error:'Choose an allocation'},400);
if(action==='allocation'&&(typeof b.category!=='string'||!b.category.trim()||b.category.length>100||typeof b.note!=='string'||b.note.length>1000||!Number.isSafeInteger(b.amount)||b.amount<1||b.amount>100000000))return json({error:'Enter a category and a positive USD amount with at most two decimal places.'},400);
const id=b.id||crypto.randomUUID();const statement=action==='allocation-delete'?db.prepare('DELETE FROM allocations WHERE id=? AND campaign=?').bind(id,b.campaign):db.prepare('INSERT INTO allocations (id,campaign,category,amount,note,updated) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET category=excluded.category,amount=excluded.amount,note=excluded.note,updated=excluded.updated').bind(id,b.campaign,b.category.trim(),b.amount,b.note.trim(),now());
await db.batch([statement,db.prepare('INSERT INTO audit (id,actor,action,created) VALUES (?,?,?,?)').bind(crypto.randomUUID(),req.headers.get('oai-authenticated-user-email'),(action==='allocation-delete'?'Removed':'Saved')+' fund allocation: '+id+' / '+b.campaign+(action==='allocation'?' / '+b.category+' / USD '+(b.amount/100).toFixed(2):''),now())]);return json({ok:true});}
if(action==='report'){if(typeof b.title!=='string'||!b.title.trim()||b.title.length>150||typeof b.body!=='string'||!b.body.trim()||b.body.length>10000||b.permissions!==true)return json({error:'Complete the report and confirm publication permissions.'},400);if(!await db.prepare('SELECT id FROM campaigns WHERE id=?').bind(b.campaign).first())return json({error:'Choose a campaign'},400);const id=crypto.randomUUID(),created=now();const statements=[db.prepare('INSERT INTO reports (id,campaign,title,body,created) VALUES (?,?,?,?,?)').bind(id,b.campaign,b.title,b.body,created)];if(b.notify){const donors=await db.prepare("SELECT DISTINCT email FROM donations WHERE campaign=? AND status='succeeded'").bind(b.campaign).all<any>();for(const d of donors.results)statements.push(db.prepare('INSERT INTO outbox (id,email,subject,body,status,created) VALUES (?,?,?,?,?,?)').bind(id+':'+d.email,d.email,b.title,b.body+'\n\nRead the campaign update: '+(config().SITE_URL||new URL(req.url).origin)+'/#updates','queued',created));if(b.campaign==='naseem'){const supporters=await db.prepare("SELECT email,token FROM subscribers WHERE active=1 AND source='launchgood-impact-naseem-v1'").all<any>();for(const supporter of supporters.results){if(donors.results.some(d=>d.email===supporter.email))continue;statements.push(db.prepare('INSERT INTO outbox (id,email,subject,body,status,created) VALUES (?,?,?,?,?,?)').bind(id+':'+supporter.email,supporter.email,b.title,b.body+'\n\nRead the update: '+(config().SITE_URL||new URL(req.url).origin)+'/#updates'+'\nUnsubscribe from impact updates: '+(config().SITE_URL||new URL(req.url).origin)+'/?token='+encodeURIComponent(supporter.token)+'#unsubscribe','queued',created));}}}await db.batch(statements);await log(req,'Published report '+id);await deliver();return json({ok:true});}
if(action==='preference'){if(!emailValid(b.email))return json({error:'Invalid email'},400);await db.batch([db.prepare('UPDATE subscribers SET active=0 WHERE email=?').bind(b.email),db.prepare('INSERT INTO audit (id,actor,action,created) VALUES (?,?,?,?)').bind(crypto.randomUUID(),req.headers.get('oai-authenticated-user-email'),'Unsubscribed '+b.email,now())]);return json({ok:true});}
if(action==='send'){if(!config().RESEND_API_KEY||!config().EMAIL_FROM)return json({error:'Connect a verified sender and email service before retrying delivery.'},409);await deliver();return json({ok:true});}
return json({error:'Not found'},404);
}catch{return json({error:'Unable to complete this request. Your input has been kept; please try again.'},503);}}